newline_style = "Unix"
tab_spaces = 2

use_field_init_shorthand = true
use_try_shorthand = true

unstable_features = true

imports_layout = "HorizontalVertical"
imports_granularity = "Crate"

spaces_around_ranges = true

format_code_in_doc_comments = true
